
[MachineConfig]

	[MachineConfig.WeatherControllerConfig]
		#Amount of Power Consumed per Tick - Default: [30FE]
		powerPerTick = 30
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineConfig.TimeControllerConfig]
		#Amount of Power Consumed per Tick - Default: [30FE]
		powerPerTick = 30
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineConfig.SimulatedHydroponicBedConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [600 (30s)]
		maxProgress = 600
		#Amount of Power Consumed per Operation - Default: [3000FE]
		powerPerOperation = 3000
		#Max Stored Power [FE] - Default: [20000 FE]
		maxStoredPower = 20000
		#Chance to increase the executions of the current processor, 0.1 = 10% chance - Default: [0.1]
		chanceToIncreaseExecutions = 0.1

	[MachineConfig.RuleControllerConfig]
		#Amount of Power Consumed per Tick - Default: [30FE]
		powerPerTick = 30
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineConfig.PlatformBuilderConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [2 (0.1s)]
		maxProgress = 2
		#Amount of Power Consumed per Operation - Default: [10FE] - This is Calculated as [VALUE * (amount + 1)]
		powerPerOperation = 500
		#Max Stored Power [FE] - Default: [20000 FE]
		maxStoredPower = 20000
		#Max Land Range [int] - Default: [18 blocks]
		maxLandRange = 18
		#Max Frame Bounds [int] - Default: [9 blocks]
		maxFrameBounds = 9

	[MachineConfig.InfuserConfig]
		#Amount of Power Consumed per Tick - Default: [90FE]
		powerPerTick = 90
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 8000

	[MachineConfig.FluidTransferConfig]
		#Max Amount of Stored Fluid - Default: [8000mB]
		maxTankSize = 8000
		#Max Amount of transfer Fluid in Progresses - Default: [1000mB]
		baseMaxTransfer = 1000
		#Default Max Connect Distance of transfer Fluid - Default: [8 block]
		defaultMaxConnectDistance = 8

	[MachineConfig.FluidCraftingTableConfig]
		#Max Amount of Stored Fluid [Input] - Default: [10000mB]
		maxInputTankSize = 10000

	[MachineConfig.DragonStarGeneratorConfig]
		#Burn Time in Ticks [20 Ticks per Second] - Default: [1200 (60s)]
		maxProgress = 1200
		#Amount of Power Produced per Tick - Default: [40000FE]
		powerPerTick = 40000
		#Max Stored Power [FE] - Default: [800000000 FE]
		maxStoredPower = 800000000
		#Amount of FE/t extracted from the Dragon Star Generator
		extractionRate = 1600000

	[MachineConfig.DragonGeneratorConfig]
		#Burn Time in Ticks [20 Ticks per Second] - Default: [2400 (120s)]
		maxProgress = 2400
		#Amount of Power Produced per Tick - Default: [4000FE]
		powerPerTick = 4000
		#Max Stored Power [FE] - Default: [800000 FE]
		maxStoredPower = 8000000
		#Amount of FE/t extracted from the Dragon Generator
		extractionRate = 160000
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 8000

	[MachineConfig.BlackHoleCapacitorConfig]
		#Pity Max Stored Power [FE] - Default: [100000 FE]
		pity = 100000
		#Simple Max Stored Power [FE] - Default: [500000 FE]
		simple = 500000
		#Advanced Max Stored Power [FE] - Default: [5000000 FE]
		advanced = 5000000
		#Supreme Max Stored Power [FE] - Default: [50000000 FE]
		supreme = 50000000

	[MachineConfig.BigDissolutionChamberConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [180FE]
		powerPerTick = 180
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 64000
		#Max Amount of Stored Fluid [Output] - Default: [8000mB]
		maxOutputTankSize = 64000
		#Default Max Thread - Default: [8]
		maxThread = 8

	[MachineConfig.ArcaneDragonForgingConfig]
		#Amount of Power Consumed per Tick - Default: [90FE]
		powerPerTick = 90
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 8000
		#Max Amount of Stored Fluid [Output] - Default: [8000mB]
		maxOutputTankSize = 8000

