
["Jade Config"]
	#Should jade show botania information?
	"Should show mana tooltip" = true
	#Should jade show advanced configs?
	#For example how much mana does a spreader pass each burst
	#This config is useless if [Should Show Mana Tooltip] is false
	"Should show advanced tooltip" = true

