
#Air Sword
[air_sword]
	#Enable Air Sword [true / false]
	airCrafting = true

#Type of sword for recipe
[sword_for_recipe]
	#Type of sword for recipe: 0 for diamond, 1 for netherite [0-1, default: 0]
	#Range: 0 ~ 1
	typeSword = 0

#Earth Sword
[earth_sword]
	#Enable Earth Sword [true / false]
	earthCrafting = true

#God Sword
[god_sword]
	#Enable God Sword [true / false]
	godCrafting = true

#Fire Sword
[fire_sword]
	#Enable Fire Sword [true / false]
	fireCrafting = true

#Water Sword
[water_sword]
	#Enable Water Sword [true / false]
	waterCrafting = true

