
["Mekanism Weaponry Config"]
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	plasmaRifleCooldown = 6
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	plasmaRifleEnergyUsage = 250
	#How many ticks it should take to reload the weapon
	#Range: > 0
	plasmaRifleReloadTime = 45
	#How much heat should accumulate every shot
	#Range: > 0
	plasmaRifleHeatPerShot = 20
	#How much energy the gun can store
	#Range: > 0
	plasmaRifleEnergyCapacity = 10000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	plasmaRifleEnergyTransfer = 1000
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	railgunCooldown = 20
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	railgunEnergyUsage = 1000
	#How many ticks it should take to reload the weapon
	#Range: > 0
	railgunReloadTime = 55
	#Max ammo the gun can hold
	#Range: > 1
	railgunMaxAmmo = 5
	#How much energy the gun can store
	#Range: > 0
	railgunEnergyCapacity = 100000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	railgunEnergyTransfer = 10000
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	teslaMinigunCooldown = 4
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	teslaMinigunEnergyUsage = 1000
	#How many ticks it should take to reload the weapon
	#Range: > 0
	teslaMinigunReloadTime = 100
	#How much heat should accumulate every shot
	#Range: > 0
	teslaMinigunHeatPerShot = 5
	#How much energy the gun can store
	#Range: > 0
	teslaMinigunEnergyCapacity = 100000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	teslaMinigunEnergyTransfer = 10000
	#How much FE should be drained from the battery every shot
	#Range: > 0
	gauntletEnergyUsage = 1000
	#How much energy the gauntlet battery can store
	#Range: > 0
	gauntletEnergyCapacity = 10000
	#How fast the gauntlet battery can charge/discharge
	#Range: > 0
	gauntletEnergyTransfer = 1000

